{% set version = "3.1.0" %}
{% set sha256 = "dc4e4a227d04d3da46ad920dfee5f7599ac8d6b2ee1809c9067110fb1cc71ced" %}

package:
  name: nvtx-c
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/NVTX/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - test -e "$PREFIX"/include/nvtx3/nvToolsExt.h  # [not win]
    - if not exist "%LIBRARY_INC%"\nvtx3\nvToolsExt.h exit 1  # [win]

about:
  home: https://nvidia.github.io/NVTX/doxygen/index.html
  summary: NVIDA Tool Extension Library (NVTX) C API
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shwina
